### ISSUE TITLE
mallinfo is deprecated

### ISSUE THREAD

**Issue by trikko** [tofuengine/tofu#3]
glibc 2.33 deprecated mallinfo in favor of mallinfo2.
More info [here](https://sourceware.org/pipermail/libc-alpha/2021-February/122207.html)

This usage:
https://github.com/tofuengine/tofu/blob/b258b777ff26e8b095184fab5909c675d6ec559c/src/core/environment.c#L170

Trigger a deprecation and an error.

```
src/core/environment.c: In function ‘Environment_process’:
src/core/environment.c:170:16: error: ‘mallinfo’ is deprecated [-Werror=deprecated-declarations]
  170 |         struct mallinfo mi = mallinfo();
      |                ^~~~~~~~
In file included from external/stb/stb_leakcheck.h:140,
                 from src/libs/stb.h:29,
                 from src/core/environment.c:29:
/usr/include/malloc.h:118:24: note: declared here
  118 | extern struct mallinfo mallinfo (void) __THROW __MALLOC_DEPRECATED;
      |                        ^~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:105: src/core/environment.o] Errore 1
```

**Comment by MarcoLizza** [comment]
The issue has been already fixed upstream back last year (!!!) in commit `de9df0170588b113f7c1478a124b4e9a392abfa0`. I totally forgot about that! :)
