### ISSUE TITLE
References to `tofu.controller:controller breaks two demos

### ISSUE THREAD

**Issue by sroccaserra** [tofuengine/tofu#4]
Hi, this is an interesting project, thank you for sharing!

I found (old?) references to the (changed?) `tofu.controller:controller` table in two demos, causing errors. Changing the refs to `tofu.input.controller` fixes them:

```diff
diff --git a/demos/scroller/main.lua b/demos/scroller/main.lua
index 38c8c6f3..f300d691 100644
--- a/demos/scroller/main.lua
+++ b/demos/scroller/main.lua
@@ -24,7 +24,7 @@ SOFTWARE.
 
 local Class = require("tofu.core.class")
 local System = require("tofu.core.system")
-local Controller = require("tofu.controller:controller")
+local Controller = require("tofu.input.controller")
 local Canvas = require("tofu.graphics.canvas")
 local Display = require("tofu.graphics.display")
 local Font = require("tofu.graphics.font")
diff --git a/demos/shades/main.lua b/demos/shades/main.lua
index 0b42e669..9c736473 100644
--- a/demos/shades/main.lua
+++ b/demos/shades/main.lua
@@ -24,7 +24,7 @@ SOFTWARE.
 
 local Class = require("tofu.core.class")
 local System = require("tofu.core.system")
-local Controller = require("tofu.controller:controller")
+local Controller = require("tofu.input.controller")
 local Canvas = require("tofu.graphics.canvas")
 local Display = require("tofu.graphics.display")
 local Font = require("tofu.graphics.font")
```

Hope this helps,
Cheers!

**Comment by MarcoLizza** [comment]
Hi! Thanks for your contribution, I'm glad you do like the project!

I've been changing the input/controller API lately, and something was left out (and the documentation -- ouch -- is very scarce at the moment)! :)

Thanks for taking the time to check and fix it, I will include you as soon as possible.

**Comment by MarcoLizza** [comment]
I (finally) checked the source code, and the issue was already fixed upstream (in the development branch). `v0.12.0` already has this fixed. :)
