### ISSUE TITLE
Compilation issues on Fedora 36

### ISSUE THREAD

**Issue by lminiero** [tofuengine/tofu#5]
I realize the instructions are for Debian, but I wanted to try and build the engine on my Fedora too, to see if/what changes may be needed. Dependencies-wise everything seems correct, as I didn't encounter problems there: I didn't have to install anything new, `make` just "worked", so I'm afraid I can't provide names for the packages that should be installed via `dnf` there (I know they're different since the ones listed for Debian don't exist on Fedora, even with a s/dev/devel).

The problem seem more on the Lua/packer side of things. Initially, `make` complained about not being able to find `./extras/pakgen.lua`, which is there though. Looking at the Makefile, I realized the cause was an attempt to run that Lua script as an executable. Inspecting the file, it starts like this:

```
#!/usr/bin/lua5.3
```

which is an interpreter that doesn't exist on Fedora, while `/usr/bin/lua` does (5.4 is installed). Not sure if Debian and other distros only provide the numbered executables, but otherwise setting just `lua` may help pass that part.

I had a different issue with luazen, which ended up being installed by `luarocks` in a folder that Lua itself couldn't find. Just linking the .so to one of the "good" places was enough to get it working (this is very likely a local issue, and so not something you should address in the repo, so it's just an FYI!).

Finally, `make` stumbled here which is where I stopped since I'm not sure how this can be fixed:

```
[lminiero@lminiero tofu]$ make
Linking complete!
Total: 0 warnings / 0 errors in 22 files
PakGen v0.4.1
=============
Fetching files from folder `./src/kernal`
Optimizing...
Creating encrypted archive `./build/kernal.pak` w/ 43 entries
/usr/bin/lua: ./extras/pakgen.lua:175: attempt to index a nil value (global 'bit32')
stack traceback:
	./extras/pakgen.lua:175: in upvalue 'compile_flags'
	./extras/pakgen.lua:195: in upvalue 'emit_header'
	./extras/pakgen.lua:314: in upvalue 'emit'
	./extras/pakgen.lua:350: in local 'main'
	./extras/pakgen.lua:359: in main chunk
	[C]: in ?
make: *** [Makefile:252: build/kernal.pak] Error 1
```

Googling around, it looks like `bit32` was removed in Lua 5.3 (since bitwise operations are now supported), but since 5.4.4 is recommended in the README, that may be incorrect. As such, not sure if it's something only missing in Fedora, or something it should indeed be able to find somewhere else.

Hope this is helpful, keep up the great work!

**Comment by MarcoLizza** [comment]
First and foremost, thanks for putting some of your time into this. I *highly* respect others' time and *deeply* appreciate it when this happens. :)

That being said, you tripped over something I totally forgot to clean up! :P On Ubuntu/Debian, Lua5.4 needs to be explicitly set as the "default alternative", as APT doesn't do it. I wanted to keep the installation procedure to be as clean as possible, so I kept using version 5.3.

Unfortunately, the `README.md` file is out of sync (as I forgot to edit it back) and gives different instructions to install *Lua 5.4*! Oops!

There are two possible solutions, to this:

1. Adding specific instructions in the `README.md` file (for Debian/Ubuntu) to install Lua 5.4 and set it as the default alternative, or
2. Referencing release 5.4 in the shebang header.

I'd rather go with option #2, honestly. Could you, please, check if Lua is accessible also as `lua5.4` on Fedora?

Thanks for letting me know! :)

**Comment by MarcoLizza** [comment]
On second thought, option (2) is preferred as it is more conservative regarding the developer environment (which, for example, could have decided to set a Lua version different from 5.4 as the default one).

I'm closing the issue.

**Comment by lminiero** [comment]
Apologies for the lack of feedback, I haven't been home much yesterday!

> Could you, please, check if Lua is accessible also as `/usr/bin/lua5.4` on Fedora?

It isn't, there's just `lua`. But I pulled the latest changes, created a symlink for `/usr/bin/lua5.4`, and that got compilation to work, thanks! Now I'm getting a segfault when `tofu` starts (whether on its own or in the context of a demo), but I'll open a different issue for that.
