### ISSUE TITLE
tiled-map demo fails to start

### ISSUE THREAD

**Issue by lminiero** [tofuengine/tofu#7]
I'm getting a guru meditation (nice Amiga callback! :laughing: ) error when starting the `tiled-map` demo, this is the exception I'm getting:

```
[E/log] lib/map.lua:71: [src/modules/canvas.c:135] signature failure for argument #1 (wrong actual type, got `string`)
stack traceback:
	[C]: in function 'tofu.graphics.canvas.new'
	lib/map.lua:71: in function 'lib/map.from_file'
	main.lua:43: in function 'main.__ctor'
	tofu/core/class.lua:33: in function 'main.new'
	boot-debug.lua:43: in function <boot-debug.lua:41>
	[C]: in function 'xpcall'
	boot-debug.lua:175: in method 'call'
	boot-debug.lua:163: in method 'switch_if_needed'
	boot-debug.lua:135: in function <boot-debug.lua:134>
```

Apparently the canvas creator expects an object (`LUAX_SIGNATURE_REQUIRED(LUA_TOBJECT)`) and is getting a string. Unfortunately I'm not familiar enough with the internals of the engine, or with how the demo is supposed to work to figure out what's wrong. All other demos work great instead, great work!

**Comment by MarcoLizza** [comment]
Apparently, I left the `tiled-map` demo unchanged when I revamped the API earlier last year. Oops! :)

That's one of the main reasons why I totally need to finish the API documentation!

( glad you appreciated the Amiga reference ;) )
